### PR TITLE
Remove spellcheck

### PR DESCRIPTION
**Pull request by morgoth**
It's failing since https://github.com/rails/website/commit/a53d8ea05a1c7df66e197a45970f69db78929b57 (see https://github.com/rails/website/actions/runs/8066396132)

Since zzak was the one that added it to the repo, we chatted if this can be fixed/ignored and he noticed that most likely this should be removed in the same way as on Rails repo.

/cc @zzak

### CODE REVIEW

**Comment by gregmolnar** [comment]
@zzak shall we merged this?

**Comment by matthewd** [comment]
Has it been problematic?

I believe it was removed from the main repo because it was requiring too many exceptions for things that aren't words, but were intended. It doesn't seem obvious to me that that would apply as strongly for the website repo, where I would imagine active spellchecking would be more clearly helpful.

**Comment by morgoth** [comment]
@matthewd It's failing since https://github.com/rails/website/commit/a53d8ea05a1c7df66e197a45970f69db78929b57 (see https://github.com/rails/website/actions/runs/8066396132)

Since zzak was the one that added it to the repo, we chatted if this can be fixed/ignored and he noticed that most likely this should be removed in the same way as on Rails repo.
(I added this explanation to the PR description which I should do when opening it)

**Comment by zzak** [comment]
Alternatively, we could add those words to [codespell.txt](https://github.com/rails/website/blob/main/codespell.txt) or add that blog post to the list of [--skip files]( https://github.com/rails/website/blob/56dd01ea073d30ea1558735cc3343918a16830f5/.github/workflows/lint.yml#L23):

```
run: codespell --ignore-words=codespell.txt --skip="./doctrine/de.html,./doctrine/es.html,./doctrine/fr.html,./.git,./_posts/200*-*,./_posts/201*-*,./assets/200*,./assets/201*,./_posts/*sao-paolo.markdown" || exit 1)
```

Matthew makes a good point about the reason codespell was removed from rails/rails, because it's a source code project where spellcheck is designed more for blogs and websites.

My feeling was it just easier to remove it than have to maintain a list of exceptions, but it doesn't seem common to be writing in non-English languages. It would be nice if there was a tool that could support that.

**Comment by morgoth** [comment]
@zzak feel free to take over and close this PR

**Comment by zzak** [comment]
I've opened #239 as an alternative :bow:

**Pull request closed without merging**
