### PR TITLE
The Rails World website

### PR DESCRIPTION
**Pull request by ayushn21**
The initial version of the Rails World website containing the homepage, speakers, FAQs, and ticket link.

Dev work by @weepotty.

### CODE REVIEW

**Comment by AmandaPerino** [comment]
Thank you for all the hard work on this @weepotty & @ayushn21 !

**Comment by fxn** [comment]
There are a bunch of "Lorem ipsum dolor...", is that expected?

**Comment by ayushn21** [comment]
@fxn Thanks for pointing that out. It's not an issue as none of those pages are visible as yet. Some pages like the speaker index and individual speaker pages are still in development and we've hidden it for this initial launch, so none of the uses of "Lorem ipsum..." are visible in the site.

We'll replace it with real content as we continue developing the site.

**Comment by fxn** [comment]
Awesome, thanks @ayushn21!

**Pull request merged**
