### PR TITLE
Update Cookpad logo to meet its branding guideline

### PR DESCRIPTION
**Pull request by sorah**
I just noticed our company logo is featured on Rails' website! We're proud of it 🤗  Thanks!

However, I'd like to update the svg file because the present one is not meeting our branding guideline (missing 🎩  symbol). I just generated one from master Illustrator file.

If you'd like to access the original logo files and guideline and generate by your own, please contact me at sorah@cookpad.com.

~ @sorah on behalf of Cookpad engineering team

### CODE REVIEW

**Comment by carlosantoniodasilva** [comment]
Hi, thanks for submitting an updated logo.  Any chance you could share a before/after screenshot for comparison and historical reference?

**Comment by sorah** [comment]
Do you want a screenshot of the webpage itself or just logo is fine?

**Comment by carlosantoniodasilva** [comment]
I was thinking about the logo within the webpage. (i.e. a small area around the logo for context, or the whole logos section)

**Comment by sorah** [comment]
## before



## after

**Comment by carlosantoniodasilva** [comment]
@sorah thank you 🙏👍

**Pull request merged**
