### PR TITLE
Corrected 'ActionDispatch route URLs' to 'ActionDispatch routes URLs'.

### LINKED ISSUE #226: Update text describing ActionDispatch?
https://github.com/rails/website/blame/4597a40aa915e9b22e63cbc55e59dd01df0d5574/index.html#L289

I am thinking 'ActionDispatch route URLs' sounds odd. I think it should be 'ActionDispatch routes URLs'?

- Active Records make modeling easy. ✅ 
- Action Controllers handle all requests. ✅ 
- Action Views mix Ruby and HTML. ✅ 
- Action Dispatch route URLs. ❓

### PR DESCRIPTION
**Pull request by aniketpatidar**
Resolves #226 
This PR addresses a minor grammatical inconsistency.

Changes Made
Corrected the text 'ActionDispatch route URLs' to 'ActionDispatch routes URLs' in index.html.

### CODE REVIEW

**Comment by Aesthetikx** [comment]
I think for consistencies sake we should retain the space between `Action` and `Dispatch` because that is how the other ones are.

**Comment by aniketpatidar** [comment]
I will make these change. Thanks!

**Comment by aniketpatidar** [comment]
I've made the updates as per your suggestion.

**Comment by zzak** [comment]
Please [squash your commits](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits). :bow:

**Comment by aniketpatidar** [comment]
Please merge this pull request.😀

**Pull request merged**
