### PR TITLE
Remove kaspth

### PR DESCRIPTION
**Pull request by kaspth**
I'm leaving Rails core and I'm not interested in being in the alumni.

### CODE REVIEW

**Comment by gregmolnar** [comment]
💔

**Comment by fxn** [comment]
💔

**Comment by amatsuda** [comment]
💔

**Comment by nbittich** [comment]
drama on rails 🍿

**Comment by iamtekeste** [comment]
you might also want to delete core-kasper.jpg

**Comment by markmead** [comment]
giphy-downsized-large

**Comment by CharlyJazz** [comment]
Can someone explain what is happening?

**Comment by DRBragg** [comment]
💔

**Comment by williamyeny** [comment]
> Can someone explain what is happening?

Check out his Twitter: @kaspth

**Comment by almokhtarbr** [comment]
:(

**Comment by mjc-gh** [comment]
💔

**Comment by zztczcx** [comment]
merged his own PR before leaving.

**Comment by defp** [comment]
good news

**Pull request merged**
