### PR TITLE
Remove pixeltrix

### PR DESCRIPTION
**Pull request by pixeltrix**

### CODE REVIEW

**Comment by fxn** [comment]
💔

**Comment by vipulnsward** [comment]
💔

**Comment by p8** [comment]
💔

**Comment by runlevel5** [comment]
❤️ respect

**Comment by pixeltrix** [comment]
Since some people require an 'explanation', I've resigned from the core team and any official capacity within the Rails community because I didn't want to be in the middle of an increasingly bitter discussion for the sake of my mental well-being. I will still be contributing to Rails as my workload permits and will still be recommending Rails to clients.

**Comment by pixeltrix** [comment]
For further clarification, I did not resign because of anything DHH has said or done - either within Rails spaces or elsewhere, only to remove myself from the online discussion which even after protecting my Twitter account and resigning is difficult to avoid being dragged into.

**Pull request merged**
